### PR TITLE
express with errorhandler module

### PR DESCRIPTION
**Pull request by kelthenoble**
A simple example running errorhandler with express  
> https://github.com/expressjs/errorhandler/pull/17

### CODE REVIEW

**Comment by kelthenoble** [comment]
Hey doug @dougwilson how can i get this puppy to invoke an error? `The code works` & but I'm trying to get it to `run erroneous`. So i could examine the output.

**Comment by dougwilson** [comment]
Hi @kelthenoble, I'm not sure what you mean. If you wanted to get an error, easiest way is to just do
```js
app.use(function(){
  throw new Error('oops!');
});
```

Also, this looks like it's a duplicate of the already-existing example https://github.com/expressjs/errorhandler#simple-example (which just says to change `connect` to `express` for that example).

I think the ultimate goal of this pull request was to actually add words to explain how the routing works, in that the error handler needs to actually be added after the routes (of course, that depends on the version of Express, as routing has changed over time).

**Comment by kelthenoble** [comment]
Would have responded sooner,  yesterday was family day. I apologize for my lackluster error-handling abilities, If i'm honest, i've spent a year+ with node & express and haven't dealt with advanced error-handling mechanisms, I say that in shame. And just 2 days ago, was really my first time looking at connect code. I say that to say this, what i lack in experience, I make up for my willingness to learn. So here is something i hope can suffice if not, I'll spend more time with error-handling and reiterate a better version to your liking. 

```js
var express = require('express');
var app = express();
var errorhandler = require('errorhandler')

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.get('/mars', function(req, res) {
  res.send('A red planet indeed!')
})

// if an error occurs then use errorhandler middleware
app.use(function(err, req, res, next) {
  if(err) {
    app.use(errorhandler)
  }
  res.send('Something broke!');
});

app.listen(3000, function () {
  console.log('app listening on port 3000');
});
```

**Comment by kelthenoble** [comment]
I been playing around with this :smile: , let me know what you think @dougwilson 
```js
var express = require('express')
var errorhandler = require('errorhandler')
var app = express()

app.use(function(req, res, next) {
  next(new Error('Hey!'))
})
// actually respond
app.use(function(req, res) {
  res.end('Hello world')
})
errorhandler.title = "errorhandler middleware"

app.use(errorhandler())
app.listen(8080)
```

**Comment by dougwilson** [comment]
Looks good, @kelthenoble! I think the ultimate goal of this pull request was to actually add words to explain how the routing works, in that the error handler needs to actually be added after the routes (of course, that depends on the version of Express, as routing has changed over time), rather than adding another Example.

**Comment by kelthenoble** [comment]
@dougwilson Okay, so what's my next move here. Which example should i add, and then add words about routing. Or should i just expand on this one -> 
screen shot 2016-02-18 at 1 34 43 pm
Or is this good as is?

**Pull request closed without merging**
