### PR TITLE
errorhandler with express

### PR DESCRIPTION
**Pull request by lordKnighton**
I had do a new one, there were issues, i got his dotfile & it threw off my gitconfig stuff
screen shot 2016-02-20 at 8 50 19 pm
 long story short, I just did a new `pull Req`. Anyway moving on.  

I hope you can use this example in your errorhandler module, Please feel free to modify it, to a more connect, routes savvy or a better version over all. 

Chatting with you has been great Doug. 

leading up to this: https://github.com/expressjs/errorhandler/pull/17 & https://github.com/expressjs/errorhandler/issues/16 & https://github.com/expressjs/errorhandler/pull/18

### CODE REVIEW

**Comment by kelthenoble** [comment]
Sorry @dougwilson I don't know what was on my mind but i skimmed over this. `actually add words to explain how the routing works` & `rather than adding another Example.`

I will fix this, I'll remove the code & go about this the correct way. As intended :100: 

> Looks good, @kelthenoble! I think the ultimate goal of this pull request was to actually add words to explain how the routing works, in that the error handler needs to actually be added after the routes (of course, that depends on the version of Express, as routing has changed over time), rather than adding another Example.

**Comment by dougwilson** [comment]
Awesome! Also, sorry, I actually forgot this pull request was here :) I just set the labels and assigned it so I wouldn't forget. Feel free to  ping me when you're ready for me to take a look :)

**Comment by kelthenoble** [comment]
Okay, will do.

**Comment by kelthenoble** [comment]
Okay so here we go @dougwilson, so i just wanted to implement a **simplistic** example with words. 
there are myriads of tutorials about routes in express out in the world, but here is an quick informative piece on `errorhandler with express` and not bogged down in a lot of code. I hope it serves well.

**Pull request closed without merging**
