### PR TITLE
link to errorhandling docs

### PR DESCRIPTION
**Pull request by kelthenoble**
https://github.com/expressjs/errorhandler/issues/16  Added link to errorHandling docs -> http://expressjs.com/en/guide/error-handling.html

### CODE REVIEW

**Comment by dougwilson** [comment]
It doesn't make sense to link to Express.js documentation when this module's examples are only `connect` and it's not tied to Express.js in any way.

**Comment by dougwilson** [comment]
I think the better documentation would be to instead describe how to use this module with Express.js inline to this README and provide the necessary information here, rather than referring to an external website that may or may not be up (this README is installed on disk, so people can review it offline).

**Comment by kelthenoble** [comment]
Yeah, you're right, I guess the name of this repo fooled me, i was thinking this was express error handler and not connect's err handler. Sorry for the mistake.

**Comment by dougwilson** [comment]
Well, you see, the "middleware pattern" is not something Express.js invented. It transcends Express.js and is used in many places, including `connect` and others. Part of that pattern is the signature of an "error handler middleware", and this module provides that :) How a particular framework chooses to actually order the middleware is a different subject. I would be happy to get added a section for Express.js to this README with information if you want to put it together, though!

**Comment by kelthenoble** [comment]
Heck yeah, i will :smile: I should have in `pull request` queue by Friday, the `latest Saturday`. Is this fine?

**Comment by dougwilson** [comment]
Yea, whenever you get to it is good to me :) I just didn't want to do it and essentially take the credit away from you if you were :)

**Comment by kelthenoble** [comment]
Oh it's no worries man, It's an `honor to contribute` to the Express Repo

**Comment by dougwilson** [comment]
And as part of the Node.js foundation, we are trying to work on getting contributing and other organizational things much more straight-forward :)

**Comment by kelthenoble** [comment]
Music to my ears :+1:

**Pull request closed without merging**
